version: '3.5'

services:
  flask_app:
    build: .  # Build the Flask app from the Dockerfile in the current directory
    ports:
      - "5000:5000"
    depends_on:
      - milvus  # Ensure Milvus starts before Flask app
    environment:
      MILVUS_HOST: milvus  # Set environment variable for Flask app
      MILVUS_PORT: 19530   # Milvus default port
    networks:
      - default  # Use the default network

  milvus:
    image: milvusdb/milvus:latest  # Pull the latest Milvus image
    restart: unless-stopped  # Restart the service if it crashes
    ports:
      - "19530:19530"  # Milvus port for communication
    networks:
      - default  # Use the default network

networks:
  default:
    driver: bridge  # Use the default bridge network
